### ISSUE TITLE
SignUp Page, set max date in signup form

### ISSUE THREAD

**Issue by m2gi-behraf** [m2gi-behraf/m2gi-devMobile-tp1#15]
On peut saisir une année de naissance dans le futur.
Mettre une date limite dynamique à la date du jour me paraît être une bonne idée.

![image](https://user-images.githubusercontent.com/43551715/223202040-04473f19-087f-4090-80f8-9dc8b726b56a.png)

Voici un lien peut-être utile:
https://stackoverflow.com/questions/56052978/how-can-i-set-min-max-date-to-current-date-in-html

**Comment by jadjawlakh** [comment]
Je suis d'accord ! Je bosserai dessus mercredi. 🫶
