### ISSUE TITLE
Images not showing anymore

### ISSUE THREAD

**Issue by m2gi-behraf** [m2gi-behraf/m2gi-devMobile-tp1#33]
Les images Facebook et google ne s'affichent plus.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/43551715/224515043-dcdbb17d-734b-414b-be44-1fd1ebe9edbf.png">

### Erreur
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/43551715/224515065-7ca0fb83-4262-46d7-8dee-6507084e0279.png">

Reproductible sur main.

**Comment by jadjawlakh** [comment]
Bizarre que ça s'affiche bien pour moi sur la branche main 
Check que t'as pull les dernieres modifs 
<img width="232" alt="Screen Shot 2023-03-12 at 00 33 04" src="https://user-images.githubusercontent.com/18511463/224516250-275e4581-78a1-44d0-93c3-2dd9f7ac4a88.png">

**Comment by jadjawlakh** [comment]
J'ai compris pourquoi... si tu passes d'une branche à une autre avant que j'ai du changer l'endroit des images, faut recompiler : donc en gros arrete la session et puis relance "ionic serve" et ça doit marcher :D 
ça vient de m'arriver aussi

**Comment by m2gi-behraf** [comment]
Raison, lors du rebase main, j'ai supprimé le changement de chemin des ressources dans login.page.html.
Les icônes n'avaient plus le bon chemin.
